// web/svelte-admin/src/lib/components/JsonEditor.svelte
<script lang="ts">
  import type { ModelMappingEntry, ModelMappingValue } from '../types';

  export let id: string;
  export let label: string;
  export let value: Record<string, ModelMappingValue>;
  export let onChange: (next: Record<string, ModelMappingValue>) => void;
  export let onErrorChange: ((error: string | null) => void) | undefined =
    undefined;
  export let placeholder: string | undefined = undefined;
  export let helperText: string | undefined = undefined;
  export let rows = 6;

  let text = '';
  let error: string | null = null;
  let isEditing = false;

  function toPrettyJson(v: Record<string, ModelMappingValue>): string {
    return JSON.stringify(v ?? {}, null, 2);
  }

  function setError(next: string | null) {
    error = next;
    onErrorChange?.(next);
  }

  function tryParseModelMapping(
    raw: string
  ):
    | { ok: true; value: Record<string, ModelMappingValue> }
    | { ok: false; error: string } {
    const trimmed = raw.trim();
    if (!trimmed) return { ok: true, value: {} };

    let parsed: unknown;
    try {
      parsed = JSON.parse(trimmed);
    } catch {
      return { ok: false, error: 'Invalid JSON' };
    }

    if (
      typeof parsed !== 'object' ||
      parsed === null ||
      Array.isArray(parsed)
    ) {
      return { ok: false, error: 'JSON must be an object' };
    }

    const mapping: Record<string, ModelMappingValue> = {};
    for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
      if (typeof v === 'string') {
        // Simple format: "gpt-4": "gpt-4-turbo"
        mapping[k] = v;
      } else if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
        // Extended format: check for mapped_model field
        const entry = v as Record<string, unknown>;
        if (typeof entry.mapped_model !== 'string') {
          return {
            ok: false,
            error: `Entry "${k}" must have a string "mapped_model" field`,
          };
        }
        mapping[k] = entry as unknown as ModelMappingEntry;
      } else {
        return {
          ok: false,
          error: `Value for "${k}" must be a string or an object with mapped_model`,
        };
      }
    }

    return { ok: true, value: mapping };
  }

  $: if (!isEditing) {
    text = toPrettyJson(value);
    setError(null);
  }

  function handleInput(nextText: string) {
    isEditing = true;
    text = nextText;

    const parsed = tryParseModelMapping(nextText);
    if (!parsed.ok) {
      setError(parsed.error);
      return;
    }

    setError(null);
    onChange(parsed.value);
  }

  function handleBlur() {
    isEditing = false;

    const parsed = tryParseModelMapping(text);
    if (!parsed.ok) return;
    text = toPrettyJson(parsed.value);
  }
</script>

<div>
  <label for={id} class="label">{label}</label>
  <textarea
    {id}
    class="input font-mono"
    {rows}
    {placeholder}
    value={text}
    aria-invalid={error ? 'true' : undefined}
    oninput={e => handleInput((e.currentTarget as HTMLTextAreaElement).value)}
    onblur={handleBlur}
  ></textarea>

  {#if helperText && !error}
    <p class="helper-text">{helperText}</p>
  {/if}
  {#if error}
    <p class="mt-1 text-xs text-red-600">{error}</p>
  {/if}
</div>

// web/react-admin/src/components/JsonEditor.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import type { ModelMappingEntry, ModelMappingValue } from '../types';

type JsonEditorProps = {
  id: string;
  label: string;
  value: Record<string, ModelMappingValue>;
  onChange: (next: Record<string, ModelMappingValue>) => void;
  onErrorChange?: (error: string | null) => void;
  placeholder?: string;
  helperText?: string;
  rows?: number;
};

function toPrettyJson(value: Record<string, ModelMappingValue>): string {
  return JSON.stringify(value ?? {}, null, 2);
}

function tryParseModelMapping(
  text: string
):
  | { ok: true; value: Record<string, ModelMappingValue> }
  | { ok: false; error: string } {
  const trimmed = text.trim();
  if (!trimmed) return { ok: true, value: {} };

  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed);
  } catch {
    return { ok: false, error: 'Invalid JSON' };
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    return { ok: false, error: 'JSON must be an object' };
  }

  const mapping: Record<string, ModelMappingValue> = {};
  for (const [key, value] of Object.entries(
    parsed as Record<string, unknown>
  )) {
    if (typeof value === 'string') {
      // Simple format: "gpt-4": "gpt-4-turbo"
      mapping[key] = value;
    } else if (
      typeof value === 'object' &&
      value !== null &&
      !Array.isArray(value)
    ) {
      // Extended format: check for mapped_model field
      const entry = value as Record<string, unknown>;
      if (typeof entry.mapped_model !== 'string') {
        return {
          ok: false,
          error: `Entry "${key}" must have a string "mapped_model" field`,
        };
      }
      mapping[key] = entry as unknown as ModelMappingEntry;
    } else {
      return {
        ok: false,
        error: `Value for "${key}" must be a string or an object with mapped_model`,
      };
    }
  }

  return { ok: true, value: mapping };
}

const JsonEditor: React.FC<JsonEditorProps> = ({
  id,
  label,
  value,
  onChange,
  onErrorChange,
  placeholder,
  helperText,
  rows = 6,
}) => {
  const [text, setText] = useState(() => toPrettyJson(value));
  const [error, setError] = useState<string | null>(null);
  const isEditingRef = useRef(false);

  const setErrorAndNotify = useCallback(
    (next: string | null) => {
      setError(next);
      onErrorChange?.(next);
    },
    [onErrorChange]
  );

  useEffect(() => {
    if (isEditingRef.current) return;
    setText(toPrettyJson(value));
    setErrorAndNotify(null);
  }, [setErrorAndNotify, value]);

  const handleChange = (nextText: string) => {
    isEditingRef.current = true;
    setText(nextText);

    const parsed = tryParseModelMapping(nextText);
    if (!parsed.ok) {
      setErrorAndNotify(parsed.error);
      return;
    }

    setErrorAndNotify(null);
    onChange(parsed.value);
  };

  const handleBlur = () => {
    isEditingRef.current = false;

    const parsed = tryParseModelMapping(text);
    if (!parsed.ok) return;

    setText(toPrettyJson(parsed.value));
  };

  return (
    <div>
      <label htmlFor={id} className="label">
        {label}
      </label>
      <textarea
        id={id}
        value={text}
        onChange={e => handleChange(e.target.value)}
        onBlur={handleBlur}
        className="input font-mono"
        rows={rows}
        placeholder={placeholder}
        aria-invalid={!!error}
      />
      {helperText && !error && <p className="helper-text">{helperText}</p>}
      {error && <p className="mt-1 text-xs text-red-600">{error}</p>}
    </div>
  );
};

export default JsonEditor;
