// web/svelte-admin/src/routes/providers/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { providers, loading, errors, actions } from '$lib/stores';
  import { generateApiKey } from '$lib/api';
  import JsonEditor from '$lib/components/JsonEditor.svelte';
  import type { Provider, ProviderFormData } from '$lib/types';
  import {
    Plus,
    Pencil,
    Trash2,
    Loader2,
    AlertCircle,
    X,
    Check,
    Shuffle,
  } from 'lucide-svelte';

  let searchTerm = $state('');
  let showCreateForm = $state(false);
  let editingProvider: Provider | null = $state(null);
  let deleteConfirm: Provider | null = $state(null);
  let formData: ProviderFormData = $state({
    provider_key: '',
    provider_type: 'openai',
    api_base: '',
    api_key: '',
    model_mapping: {},
    is_enabled: true,
  });
  let modelMappingError = $state<string | null>(null);

  // Load providers on mount
  onMount(() => {
    actions.loadProviders();
  });

  // Filtered providers based on search
  const filteredProviders = $derived(
    $providers.filter(
      provider =>
        provider &&
        provider.provider_key &&
        (provider.provider_key
          .toLowerCase()
          .includes(searchTerm.toLowerCase()) ||
          provider.provider_type
            .toLowerCase()
            .includes(searchTerm.toLowerCase()) ||
          provider.api_base.toLowerCase().includes(searchTerm.toLowerCase()))
    )
  );

  function resetForm() {
    formData = {
      provider_key: '',
      provider_type: 'openai',
      api_base: '',
      api_key: '',
      model_mapping: {},
      is_enabled: true,
    };
    modelMappingError = null;
    editingProvider = null;
    showCreateForm = false;
  }

  function handleCreate() {
    resetForm();
    showCreateForm = true;
  }

  function handleEdit(provider: Provider) {
    editingProvider = provider;
    formData = {
      provider_key: provider.provider_key,
      provider_type: provider.provider_type,
      api_base: provider.api_base,
      api_key: '', // Don't populate existing key for security
      model_mapping: provider.model_mapping,
      is_enabled: provider.is_enabled,
    };
    modelMappingError = null;
    showCreateForm = true;
  }

  async function handleSubmit() {
    if (modelMappingError) return;

    if (editingProvider) {
      // Update existing provider
      const updateData: Record<string, unknown> = {
        provider_type: formData.provider_type,
        api_base: formData.api_base,
        model_mapping: formData.model_mapping,
        is_enabled: formData.is_enabled,
      };

      // Only include API key if it's provided
      if (formData.api_key.trim()) {
        updateData.api_key = formData.api_key;
      }

      const success = await actions.updateProvider(
        editingProvider.id,
        updateData
      );
      if (success) {
        resetForm();
      }
    } else {
      // Create new provider
      const success = await actions.createProvider(formData);
      if (success) {
        resetForm();
      }
    }
  }

  async function handleDelete(provider: Provider) {
    const success = await actions.deleteProvider(provider.id);
    if (success) {
      deleteConfirm = null;
    }
  }

  async function handleToggleStatus(provider: Provider) {
    await actions.toggleProviderStatus(provider.id, !provider.is_enabled);
  }

  function generateRandomKey() {
    formData.api_key = generateApiKey();
  }
</script>

<svelte:head>
  <title>Providers - LLM Proxy Admin</title>
</svelte:head>

<div class="space-y-6">
  <!-- Header -->
  <div class="flex justify-between items-center">
    <div>
      <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">
        Providers
      </h1>
      <p class="text-gray-600 dark:text-gray-400">
        Manage your LLM provider configurations
      </p>
    </div>
    <button
      onclick={handleCreate}
      class="btn btn-primary flex items-center space-x-2"
    >
      <Plus class="w-5 h-5" />
      <span>Add Provider</span>
    </button>
  </div>

  <!-- Search -->
  <div class="max-w-md">
    <input
      type="text"
      placeholder="Search providers..."
      bind:value={searchTerm}
      class="input"
    />
  </div>

  <!-- Error Display -->
  {#if $errors.providers}
    <div class="alert-error">
      <div class="flex">
        <div class="shrink-0">
          <AlertCircle class="h-5 w-5 text-red-400" />
        </div>
        <div class="ml-3">
          <p class="text-sm text-red-700">{$errors.providers}</p>
        </div>
        <div class="ml-auto pl-3">
          <button
            onclick={() => actions.clearError('providers')}
            class="text-red-400 hover:text-red-600"
          >
            <X class="h-5 w-5" />
          </button>
        </div>
      </div>
    </div>
  {/if}

  <!-- Create/Edit Form Modal -->
  {#if showCreateForm}
    <div
      class="modal-overlay"
      onclick={resetForm}
      onkeydown={e => e.key === 'Escape' && resetForm()}
      role="button"
      tabindex="0"
      aria-label="Close modal"
    >
      <div
        class="modal"
        onclick={e => e.stopPropagation()}
        onkeydown={e => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        tabindex="-1"
      >
        <div class="modal-header">
          <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
            {editingProvider ? 'Edit Provider' : 'Add Provider'}
          </h3>
          <button onclick={resetForm} class="btn-icon">
            <X class="w-5 h-5" />
          </button>
        </div>

        <form
          onsubmit={e => {
            e.preventDefault();
            handleSubmit();
          }}
          class="modal-body space-y-4"
        >
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label for="provider_key" class="label"> Provider Key </label>
              <input
                id="provider_key"
                type="text"
                bind:value={formData.provider_key}
                disabled={!!editingProvider}
                class="input"
                placeholder="e.g., openai-primary"
                required={!editingProvider}
              />
            </div>

            <div>
              <label for="provider_type" class="label"> Provider Type </label>
              <select
                id="provider_type"
                bind:value={formData.provider_type}
                class="input"
                required
              >
                <option value="openai">OpenAI</option>
                <option value="azure">Azure OpenAI</option>
                <option value="anthropic">Anthropic</option>
                <option value="google">Google</option>
                <option value="custom">Custom</option>
              </select>
            </div>
          </div>

          <div>
            <label for="api_base" class="label"> API Base URL </label>
            <input
              id="api_base"
              type="url"
              bind:value={formData.api_base}
              class="input"
              placeholder="https://api.openai.com/v1"
              required
            />
          </div>

          <div>
            <label for="api_key" class="label">
              API Key {editingProvider ? '(leave empty to keep current)' : ''}
            </label>
            <div class="flex space-x-2">
              <input
                id="api_key"
                type="password"
                bind:value={formData.api_key}
                class="input flex-1"
                placeholder={editingProvider
                  ? 'Enter new API key...'
                  : 'sk-...'}
                required={!editingProvider}
              />
              <button
                type="button"
                onclick={generateRandomKey}
                class="btn btn-secondary flex items-center space-x-2"
                title="Generate random key"
              >
                <Shuffle class="w-4 h-4" />
              </button>
            </div>
          </div>

          <div>
            <JsonEditor
              id="model_mapping"
              label="Model Mapping (optional)"
              value={formData.model_mapping}
              onChange={next => (formData.model_mapping = next)}
              onErrorChange={err => (modelMappingError = err)}
              rows={6}
              placeholder={`{\n  "gpt-4": "gpt-4-turbo",\n  "gpt-3.5-turbo": "gpt-3.5-turbo-16k"\n}`}
              helperText={'JSON object in format: {"source_model":"target_model"}'}
            />
          </div>

          <div class="flex items-center">
            <input
              id="is_enabled"
              type="checkbox"
              bind:checked={formData.is_enabled}
              class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
            />
            <label
              for="is_enabled"
              class="ml-2 block text-sm text-gray-900 dark:text-gray-100"
            >
              Enable this provider
            </label>
          </div>
        </form>

        <div class="modal-footer">
          <button type="button" onclick={resetForm} class="btn btn-secondary">
            Cancel
          </button>
          <button
            type="button"
            onclick={handleSubmit}
            class="btn btn-primary flex items-center space-x-2"
            disabled={$loading.providers || !!modelMappingError}
          >
            {#if $loading.providers}
              <Loader2 class="w-4 h-4 animate-spin" />
            {/if}
            <span>{editingProvider ? 'Update' : 'Create'} Provider</span>
          </button>
        </div>
      </div>
    </div>
  {/if}

  <!-- Providers List -->
  <div class="card">
    <div class="card-header flex justify-between items-center">
      <h2 class="card-title">Providers ({filteredProviders.length})</h2>
      {#if $loading.providers}
        <div class="flex items-center text-gray-500 dark:text-gray-400">
          <Loader2 class="w-5 h-5 animate-spin mr-2" />
          <span class="text-sm">Loading...</span>
        </div>
      {/if}
    </div>

    <div class="card-body p-0">
      {#if filteredProviders.length === 0}
        <div class="text-center py-12 text-gray-500 dark:text-gray-400">
          {searchTerm
            ? 'No providers match your search.'
            : 'No providers configured yet.'}
        </div>
      {:else}
        <div class="table-container">
          <table class="table">
            <thead>
              <tr>
                <th>Provider</th>
                <th>Type</th>
                <th>API Base</th>
                <th>Models</th>
                <th>Status</th>
                <th class="text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {#each filteredProviders as provider (provider.id)}
                <tr>
                  <td>
                    <div
                      class="text-sm font-medium text-gray-900 dark:text-gray-100"
                    >
                      {provider.provider_key}
                    </div>
                    <div class="text-xs text-gray-500 dark:text-gray-400">
                      ID: {provider.id}
                    </div>
                  </td>
                  <td>
                    <span class="badge badge-info">
                      {provider.provider_type}
                    </span>
                  </td>
                  <td>
                    <div
                      class="text-sm text-gray-900 dark:text-gray-100 max-w-xs truncate"
                      title={provider.api_base}
                    >
                      {provider.api_base}
                    </div>
                  </td>
                  <td>
                    <div class="text-sm text-gray-500 dark:text-gray-400">
                      {Object.keys(provider.model_mapping).length} mappings
                    </div>
                  </td>
                  <td>
                    <button
                      onclick={() => handleToggleStatus(provider)}
                      class="badge transition-colors {provider.is_enabled
                        ? 'badge-success hover:opacity-80'
                        : 'badge-danger hover:opacity-80'}"
                    >
                      {#if provider.is_enabled}
                        <Check class="w-3 h-3 mr-1" />
                        Enabled
                      {:else}
                        <X class="w-3 h-3 mr-1" />
                        Disabled
                      {/if}
                    </button>
                  </td>
                  <td>
                    <div class="flex justify-end space-x-2">
                      <button
                        onclick={() => handleEdit(provider)}
                        class="btn-icon text-primary-600 hover:text-primary-900"
                        title="Edit provider"
                      >
                        <Pencil class="w-4 h-4" />
                      </button>
                      <button
                        onclick={() => (deleteConfirm = provider)}
                        class="btn-icon text-red-600 hover:text-red-900"
                        title="Delete provider"
                      >
                        <Trash2 class="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </div>
  </div>

  <!-- Delete Confirmation Modal -->
  {#if deleteConfirm}
    <div
      class="modal-overlay"
      onclick={() => (deleteConfirm = null)}
      onkeydown={e => e.key === 'Escape' && (deleteConfirm = null)}
      role="button"
      tabindex="0"
      aria-label="Close modal"
    >
      <div
        class="modal"
        onclick={e => e.stopPropagation()}
        onkeydown={e => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        tabindex="-1"
      >
        <div class="modal-header">
          <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
            Delete Provider
          </h3>
          <button onclick={() => (deleteConfirm = null)} class="btn-icon">
            <X class="w-5 h-5" />
          </button>
        </div>
        <div class="modal-body">
          <p class="text-sm text-gray-600 dark:text-gray-400">
            Are you sure you want to delete provider
            <strong>{deleteConfirm.provider_key}</strong>? This action cannot be
            undone.
          </p>
        </div>
        <div class="modal-footer">
          <button
            onclick={() => (deleteConfirm = null)}
            class="btn btn-secondary"
          >
            Cancel
          </button>
          <button
            onclick={() => deleteConfirm && handleDelete(deleteConfirm)}
            class="btn btn-danger flex items-center space-x-2"
            disabled={$loading.providers}
          >
            {#if $loading.providers}
              <Loader2 class="w-4 h-4 animate-spin" />
            {/if}
            <span>Delete</span>
          </button>
        </div>
      </div>
    </div>
  {/if}
</div>

// web/react-admin/src/pages/Providers.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../hooks/useAuth';
import { generateApiKey } from '../api/client';
import JsonEditor from '../components/JsonEditor';
import {
  Plus,
  Pencil,
  Trash2,
  Loader2,
  AlertCircle,
  X,
  Check,
  Shuffle,
} from 'lucide-react';
import type { Provider, ProviderFormData, ProviderUpdate } from '../types';

const Providers: React.FC = () => {
  const { apiClient } = useAuth();
  const [providers, setProviders] = useState<Provider[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [editingProvider, setEditingProvider] = useState<Provider | null>(null);
  const [deleteConfirm, setDeleteConfirm] = useState<Provider | null>(null);
  const [modelMappingError, setModelMappingError] = useState<string | null>(
    null
  );
  const [formData, setFormData] = useState<ProviderFormData>({
    provider_key: '',
    provider_type: 'openai',
    api_base: '',
    api_key: '',
    model_mapping: {},
    is_enabled: true,
  });

  const loadProviders = useCallback(async () => {
    if (!apiClient) return;

    setLoading(true);
    setError(null);

    try {
      const response = await apiClient.listProviders();
      setProviders(response.providers);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load providers');
    } finally {
      setLoading(false);
    }
  }, [apiClient]);

  // Load providers when apiClient becomes available
  useEffect(() => {
    if (apiClient) {
      loadProviders();
    }
  }, [apiClient, loadProviders]);

  const resetForm = () => {
    setFormData({
      provider_key: '',
      provider_type: 'openai',
      api_base: '',
      api_key: '',
      model_mapping: {},
      is_enabled: true,
    });
    setModelMappingError(null);
    setEditingProvider(null);
    setShowCreateForm(false);
  };

  const handleCreate = () => {
    resetForm();
    setShowCreateForm(true);
  };

  const handleEdit = (provider: Provider) => {
    setEditingProvider(provider);
    setModelMappingError(null);
    setFormData({
      provider_key: provider.provider_key,
      provider_type: provider.provider_type,
      api_base: provider.api_base,
      api_key: '', // Don't populate existing key for security
      model_mapping: provider.model_mapping,
      is_enabled: provider.is_enabled,
    });
    setShowCreateForm(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!apiClient) return;
    if (modelMappingError) return;

    setLoading(true);
    setError(null);

    try {
      if (editingProvider) {
        // Update existing provider
        const updateData: ProviderUpdate = {
          provider_type: formData.provider_type,
          api_base: formData.api_base,
          model_mapping: formData.model_mapping,
          is_enabled: formData.is_enabled,
        };

        // Only include API key if it's provided
        if (formData.api_key.trim()) {
          updateData.api_key = formData.api_key;
        }

        await apiClient.updateProvider(editingProvider.id, updateData);
      } else {
        // Create new provider
        await apiClient.createProvider({
          provider_key: formData.provider_key,
          provider_type: formData.provider_type,
          api_base: formData.api_base,
          api_key: formData.api_key,
          model_mapping: formData.model_mapping,
        });
      }

      resetForm();
      await loadProviders();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save provider');
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (provider: Provider) => {
    if (!apiClient) return;

    setLoading(true);
    setError(null);

    try {
      await apiClient.deleteProvider(provider.id);
      setDeleteConfirm(null);
      await loadProviders();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : 'Failed to delete provider'
      );
    } finally {
      setLoading(false);
    }
  };

  const handleToggleStatus = async (provider: Provider) => {
    if (!apiClient) return;

    try {
      await apiClient.setProviderStatus(provider.id, !provider.is_enabled);
      await loadProviders();
    } catch (err) {
      setError(
        err instanceof Error ? err.message : 'Failed to update provider status'
      );
    }
  };

  const generateRandomKey = () => {
    setFormData(prev => ({ ...prev, api_key: generateApiKey() }));
  };

  // Filtered providers based on search
  const filteredProviders = providers.filter(
    provider =>
      provider.provider_key.toLowerCase().includes(searchTerm.toLowerCase()) ||
      provider.provider_type.toLowerCase().includes(searchTerm.toLowerCase()) ||
      provider.api_base.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
            Providers
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Manage your LLM provider configurations
          </p>
        </div>
        <button
          onClick={handleCreate}
          className="btn btn-primary flex items-center space-x-2"
        >
          <Plus className="w-5 h-5" />
          <span>Add Provider</span>
        </button>
      </div>

      {/* Search */}
      <div className="max-w-md">
        <input
          type="text"
          placeholder="Search providers..."
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
          className="input"
        />
      </div>

      {/* Error Display */}
      {error && (
        <div className="alert-error">
          <div className="flex">
            <div className="shrink-0">
              <AlertCircle className="h-5 w-5 text-red-400" />
            </div>
            <div className="ml-3">
              <p className="text-sm text-red-700">{error}</p>
            </div>
            <div className="ml-auto pl-3">
              <button
                onClick={() => setError(null)}
                className="text-red-400 hover:text-red-600"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Create/Edit Form Modal */}
      {showCreateForm && (
        <div className="modal-overlay" onClick={resetForm}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                {editingProvider ? 'Edit Provider' : 'Add Provider'}
              </h3>
              <button onClick={resetForm} className="btn-icon">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="modal-body space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label htmlFor="provider_key" className="label">
                    Provider Key
                  </label>
                  <input
                    id="provider_key"
                    type="text"
                    value={formData.provider_key}
                    onChange={e =>
                      setFormData(prev => ({
                        ...prev,
                        provider_key: e.target.value,
                      }))
                    }
                    disabled={!!editingProvider}
                    className="input"
                    placeholder="e.g., openai-primary"
                    required={!editingProvider}
                  />
                </div>

                <div>
                  <label htmlFor="provider_type" className="label">
                    Provider Type
                  </label>
                  <select
                    id="provider_type"
                    value={formData.provider_type}
                    onChange={e =>
                      setFormData(prev => ({
                        ...prev,
                        provider_type: e.target.value,
                      }))
                    }
                    className="input"
                    required
                  >
                    <option value="openai">OpenAI</option>
                    <option value="azure">Azure OpenAI</option>
                    <option value="anthropic">Anthropic</option>
                    <option value="google">Google</option>
                    <option value="custom">Custom</option>
                  </select>
                </div>
              </div>

              <div>
                <label htmlFor="api_base" className="label">
                  API Base URL
                </label>
                <input
                  id="api_base"
                  type="url"
                  value={formData.api_base}
                  onChange={e =>
                    setFormData(prev => ({ ...prev, api_base: e.target.value }))
                  }
                  className="input"
                  placeholder="https://api.openai.com/v1"
                  required
                />
              </div>

              <div>
                <label htmlFor="api_key" className="label">
                  API Key{' '}
                  {editingProvider ? '(leave empty to keep current)' : ''}
                </label>
                <div className="flex space-x-2">
                  <input
                    id="api_key"
                    type="password"
                    value={formData.api_key}
                    onChange={e =>
                      setFormData(prev => ({
                        ...prev,
                        api_key: e.target.value,
                      }))
                    }
                    className="input flex-1"
                    placeholder={
                      editingProvider ? 'Enter new API key...' : 'sk-...'
                    }
                    required={!editingProvider}
                  />
                  <button
                    type="button"
                    onClick={generateRandomKey}
                    className="btn btn-secondary flex items-center space-x-2"
                    title="Generate random key"
                  >
                    <Shuffle className="w-4 h-4" />
                  </button>
                </div>
              </div>

              <div>
                <JsonEditor
                  id="model_mapping"
                  label="Model Mapping (optional)"
                  value={formData.model_mapping}
                  onChange={next =>
                    setFormData(prev => ({ ...prev, model_mapping: next }))
                  }
                  onErrorChange={setModelMappingError}
                  rows={6}
                  placeholder='{\n  "gpt-4": "gpt-4-turbo",\n  "gpt-3.5-turbo": "gpt-3.5-turbo-16k"\n}'
                  helperText='JSON object in format: {"source_model":"target_model"}'
                />
              </div>

              <div className="flex items-center">
                <input
                  id="is_enabled"
                  type="checkbox"
                  checked={formData.is_enabled}
                  onChange={e =>
                    setFormData(prev => ({
                      ...prev,
                      is_enabled: e.target.checked,
                    }))
                  }
                  className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                />
                <label
                  htmlFor="is_enabled"
                  className="ml-2 block text-sm text-gray-900 dark:text-gray-100"
                >
                  Enable this provider
                </label>
              </div>
            </form>

            <div className="modal-footer">
              <button
                type="button"
                onClick={resetForm}
                className="btn btn-secondary"
              >
                Cancel
              </button>
              <button
                type="submit"
                onClick={handleSubmit}
                className="btn btn-primary flex items-center space-x-2"
                disabled={loading || !!modelMappingError}
              >
                {loading && <Loader2 className="w-4 h-4 animate-spin" />}
                <span>{editingProvider ? 'Update' : 'Create'} Provider</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Providers List */}
      <div className="card">
        <div className="card-header flex justify-between items-center">
          <h2 className="card-title">Providers ({filteredProviders.length})</h2>
          {loading && (
            <div className="flex items-center text-gray-500 dark:text-gray-400">
              <Loader2 className="w-5 h-5 animate-spin mr-2" />
              <span className="text-sm">Loading...</span>
            </div>
          )}
        </div>

        <div className="card-body p-0">
          {filteredProviders.length === 0 ? (
            <div className="text-center py-12 text-gray-500 dark:text-gray-400">
              {searchTerm
                ? 'No providers match your search.'
                : 'No providers configured yet.'}
            </div>
          ) : (
            <div className="table-container">
              <table className="table">
                <thead>
                  <tr>
                    <th>Provider</th>
                    <th>Type</th>
                    <th>API Base</th>
                    <th>Models</th>
                    <th>Status</th>
                    <th className="text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredProviders.map(provider => (
                    <tr key={provider.id}>
                      <td>
                        <div className="text-sm font-medium text-gray-900 dark:text-gray-100">
                          {provider.provider_key}
                        </div>
                        <div className="text-xs text-gray-500 dark:text-gray-400">
                          ID: {provider.id}
                        </div>
                      </td>
                      <td>
                        <span className="badge badge-info">
                          {provider.provider_type}
                        </span>
                      </td>
                      <td>
                        <div
                          className="text-sm text-gray-900 dark:text-gray-100 max-w-xs truncate"
                          title={provider.api_base}
                        >
                          {provider.api_base}
                        </div>
                      </td>
                      <td>
                        <div className="text-sm text-gray-500 dark:text-gray-400">
                          {Object.keys(provider.model_mapping).length} mappings
                        </div>
                      </td>
                      <td>
                        <button
                          onClick={() => handleToggleStatus(provider)}
                          className={`badge transition-colors ${
                            provider.is_enabled
                              ? 'badge-success hover:opacity-80'
                              : 'badge-danger hover:opacity-80'
                          }`}
                        >
                          {provider.is_enabled ? (
                            <>
                              <Check className="w-3 h-3 mr-1" />
                              Enabled
                            </>
                          ) : (
                            <>
                              <X className="w-3 h-3 mr-1" />
                              Disabled
                            </>
                          )}
                        </button>
                      </td>
                      <td>
                        <div className="flex justify-end space-x-2">
                          <button
                            onClick={() => handleEdit(provider)}
                            className="btn-icon text-primary-600 hover:text-primary-900"
                            title="Edit provider"
                          >
                            <Pencil className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => setDeleteConfirm(provider)}
                            className="btn-icon text-red-600 hover:text-red-900"
                            title="Delete provider"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirm && (
        <div className="modal-overlay" onClick={() => setDeleteConfirm(null)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                Delete Provider
              </h3>
              <button
                onClick={() => setDeleteConfirm(null)}
                className="btn-icon"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="modal-body">
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Are you sure you want to delete provider{' '}
                <strong>{deleteConfirm.provider_key}</strong>? This action
                cannot be undone.
              </p>
            </div>
            <div className="modal-footer">
              <button
                onClick={() => setDeleteConfirm(null)}
                className="btn btn-secondary"
              >
                Cancel
              </button>
              <button
                onClick={() => handleDelete(deleteConfirm)}
                className="btn btn-danger flex items-center space-x-2"
                disabled={loading}
              >
                {loading && <Loader2 className="w-4 h-4 animate-spin" />}
                <span>Delete</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Providers;
