// web/react-admin/src/components/Toast.tsx
import { useState } from 'react';
import { X, CheckCircle, AlertCircle, Info, AlertTriangle } from 'lucide-react';
import { useToast } from '../hooks/useToast';
import type { Toast as ToastType } from '../contexts/toast-context';

const iconMap = {
  success: CheckCircle,
  error: AlertCircle,
  info: Info,
  warning: AlertTriangle,
};

const colorMap = {
  success: 'toast-success text-green-700 dark:text-green-400',
  error: 'toast-error text-red-700 dark:text-red-400',
  info: 'toast-info text-blue-700 dark:text-blue-400',
  warning: 'toast-warning text-yellow-700 dark:text-yellow-400',
};

function ToastItem({ toast }: { toast: ToastType }) {
  const { removeToast } = useToast();
  const [isExiting, setIsExiting] = useState(false);
  const Icon = iconMap[toast.type];

  const handleClose = () => {
    setIsExiting(true);
    setTimeout(() => removeToast(toast.id), 150);
  };

  return (
    <div
      className={`toast ${colorMap[toast.type]} ${
        isExiting ? 'animate-[slideOutRight_0.15s_ease-in_forwards]' : ''
      }`}
      role="alert"
      aria-live="polite"
    >
      <div className="flex items-start gap-3">
        <Icon className="w-5 h-5 shrink-0 mt-0.5" />
        <p className="flex-1 text-sm text-gray-900 dark:text-gray-100">
          {toast.message}
        </p>
        <button
          onClick={handleClose}
          className="btn-icon p-1 -m-1 shrink-0"
          aria-label="Dismiss"
        >
          <X className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}

export function ToastContainer() {
  const { toasts } = useToast();

  if (toasts.length === 0) return null;

  return (
    <div
      className="toast-container"
      aria-live="polite"
      aria-label="Notifications"
    >
      {toasts.map(toast => (
        <ToastItem key={toast.id} toast={toast} />
      ))}
    </div>
  );
}

// web/svelte-admin/src/lib/components/Toast.svelte
<script lang="ts">
  import { toasts, type Toast } from '$lib/toast';
  import { CheckCircle, XCircle, Info, AlertTriangle, X } from 'lucide-svelte';

  const iconMap = {
    success: CheckCircle,
    error: XCircle,
    info: Info,
    warning: AlertTriangle,
  };

  const colorMap = {
    success: 'text-green-500',
    error: 'text-red-500',
    info: 'text-blue-500',
    warning: 'text-yellow-500',
  };

  const borderMap = {
    success: 'border-l-green-500',
    error: 'border-l-red-500',
    info: 'border-l-blue-500',
    warning: 'border-l-yellow-500',
  };
</script>

{#if $toasts.length > 0}
  <div
    class="fixed bottom-4 right-4 z-50 space-y-2"
    role="region"
    aria-label="Notifications"
    aria-live="polite"
  >
    {#each $toasts as toast (toast.id)}
      {@const Icon = iconMap[toast.type]}
      <div
        class="flex items-start space-x-3 bg-white dark:bg-gray-800 shadow-lg rounded-lg border border-gray-200 dark:border-gray-700 border-l-4 {borderMap[
          toast.type
        ]} p-4 min-w-[300px] max-w-md {toast.isExiting
          ? 'animate-slide-out-right'
          : 'animate-fade-in'}"
        role="alert"
      >
        <Icon class="w-5 h-5 shrink-0 {colorMap[toast.type]}" />
        <p class="flex-1 text-sm text-gray-900 dark:text-gray-100">
          {toast.message}
        </p>
        <button
          type="button"
          class="shrink-0 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
          onclick={() => toasts.remove(toast.id)}
          aria-label="Close notification"
        >
          <X class="w-4 h-4" />
        </button>
      </div>
    {/each}
  </div>
{/if}
